- hosts: all
  become: yes
  tasks:
   
   - name: install yum utils
     yum: 
       name: yum-utils
       state: latest
   
   - name: add repo
     shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo 
     
   - name: install Docker 
     yum:
       name: docker
       state: present
       update_cache: true
       skip_broken: yes
   - name: install APT Transport HTTPS
     yum:
       name: varnish 
       state: present

   - name: add Kubernetes repo  
     ansible.builtin.template:
       src: kubernetes.repo 
       dest: /etc/yum.repos.d/kubernetes.repo
       owner: root
       group: root
       mode: '0644'


   - name: install kubelet
     yum:
       name: kubelet
       state: present
       update_cache: true

   - name: install kubeadm
     yum:
       name: kubeadm
       state: present

- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     yum:
       name: kubectl
       state: latest     
